apiVersion: v1
kind: Service
metadata:
  name: backend-service-load-balancer
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
  selector:
    app: backend
